= База карт

Здесь собраны все карты, доступные в текущей версии Middara Helper.

[NOTE]
Данные карт хранятся в файле https://github.com/Koshlensky/middara-helper/blob/main/app/src/main/assets/cards.json[cards.json] в исходном коде приложения. Раздел обновляется по мере добавления новых карт.

== Типы карт

В приложении используются следующие типы карт:

[%header, cols="1a,2a"]
|===
^.^|Тип ^.^|Описание

^.^|`HERO_SHEET`
|Лист героя -- основная карта персонажа с характеристиками

^.^|`WEAPON`
|Оружие -- карты атаки и боевых предметов

^.^|`ARMOR`
|Броня -- защитное снаряжение

^.^|`TRINKET`
|Безделушки -- вспомогательные предметы

^.^|`RELIC`
|Реликвии -- редкие и мощные артефакты

^.^|`ITEM_UPGRADE`
|Улучшения предметов -- модификации для снаряжения

^.^|`BACKPACK`
|Рюкзак -- карты для хранения и расходуемых предметов

^.^|`DISCIPLINE`
|Дисциплина -- карты специализации и умений
|===

== Формат данных карты

Каждая карта в базе описана следующими полями:

* *id* -- уникальный идентификатор
* *name* -- название карты
* *type* -- тип (см. таблицу выше)
* *cardSet* -- набор, к которому относится карта
* *imageRes* -- имя файла изображения в ресурсах приложения

Подробнее о формате данных читайте в xref:../advanced/content-guide.adoc[руководстве по наполнению контентом].

== Как добавить карту

Для добавления новых карт в базу необходимо изменить файл `cards.json` и добавить изображение в ресурсы приложения, после чего пересобрать APK.

Пошаговая инструкция -- в разделе xref:../advanced/content-guide.adoc[Наполнение контентом].
